version: "3"
services:
  clickhouse-server: 
    container_name: clickhouse-server
    image: yandex/clickhouse-server
    ports:
     - "8123:8123"
     - "9000:9000"
     - "9009:9009"
    ulimits:
      nproc: 65535
      nofile:
       soft: 262144
       hard: 262144
    volumes:
      - "/data/xjj/clickhouse:/var/lib/clickhouse"
  clickhouse-client:
    image: yandex/clickhouse-client
    command: ['--host', 'clickhouse-server']